language: c
sudo: false # only for faster builds
script:
  - gcc -std=c99 -g -Wall -IBackend/Roderick/Inc -IBackend/Roderick/Drivers/STM32F3xx_HAL_Driver/Inc -IBackend/Roderick/Drivers/STM32F3xx_HAL_Driver/Inc/Legacy -IBackend/Roderick/Drivers/CMSIS/Device/ST/STM32F3xx/Include -IBackend/Roderick/Drivers/CMSIS/Include -c Backend/Roderick/Src/main.c -o main
  - gcov Backend/Roderick/Src/main.c
